# permissions for end users to edit flippers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flipper-editor-role
rules:
- apiGroups:
  - intuit.my.domain
  resources:
  - flippers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - intuit.my.domain
  resources:
  - flippers/status
  verbs:
  - get
